// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DemoPreview: typeof import('./src/components/DemoPreview.vue')['default']
    DrawerItemLink: typeof import('./src/components/DrawerItemLink.vue')['default']
    GButton: typeof import('@groggy-ui/vue')['GButton']
    GCard: typeof import('@groggy-ui/vue')['GCard']
    GCheckbox: typeof import('@groggy-ui/vue')['GCheckbox']
    GIcon: typeof import('@groggy-ui/vue')['GIcon']
    GIconButton: typeof import('@groggy-ui/vue')['GIconButton']
    GInput: typeof import('@groggy-ui/vue')['GInput']
    GList: typeof import('@groggy-ui/vue')['GList']
    GListItem: typeof import('@groggy-ui/vue')['GListItem']
    GRadio: typeof import('@groggy-ui/vue')['GRadio']
    GSelect: typeof import('@groggy-ui/vue')['GSelect']
    GSpinner: typeof import('@groggy-ui/vue')['GSpinner']
    GSwitch: typeof import('@groggy-ui/vue')['GSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export { }
